name=quickMap
version=1.0.0
author=Holman Buenaventura <habuenav@hotmail.com>
maintainer=Holman Buenaventura <habuenav@hotmail.com>
sentence=An ultra-fast and versatile alternative to Arduino's map() function using floats.
paragraph=Designed for critical performance in audio systems, synthesis, and high-speed sensor reading. Precalculates slope and offset to eliminate runtime splits. Supports inverted ranges and automatic constraints.
category=Signal Input/Output
url=https://github.com/habuenav/quickMap
architectures=*
depends=
